console.log("Hello World");
var x=10;
const a="10";
let y="hell";
console.log(x);
console.log(typeof x);
console.log(x-a);
console.log(x-parseInt(a));
var d;
console.log(typeof d);
var d=null;
console.log(typeof d);
var t=98765431234569876543n;
console.log(typeof t);